version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: bank-postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: bank
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
